services:
  warmachine-portfolio:
    build:
      context: .
      network: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: warmachine-dashboard
    network_mode: host
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
